owner: pompompur1nn # GitHub username
repo: pompompur11n.github.io # GitHub repository name
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0
sites: # List of endpoints to track
  - name: pomsaddons
    url: https://pomsaddons.xyz
  - name: ropro
    url: https://ropro.io
  - name: tames site
    url: https://tame.wtf
assignees: # Users to assign downtime issues (optional)
  - pompompur11n
